apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __APP_NAME__-prod
spec:
  project: __ARGO_PROJECT__
  destination:
    namespace: __APP_NAME__-prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/intility/__REPO_NAME__.git
    targetRevision: HEAD
    path: k8s/overlays/prod
