apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/high-availability

labels:
  - pairs:
      app.kubernetes.io/part-of: __APP_NAME__-prod
  - includeSelectors: true
    pairs:
      environment: prod

patches:
  - target:
      kind: Ingress
      name: __APP_NAME__
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: __APP_NAME__.intility.com
      - op: replace
        path: /metadata/labels/ingress-tenant
        value: default

# x-release-please-start-version
images:
  - name: ghcr.io/intility/__DOCKER_IMAGE_NAME__
    newTag: 0.0.0
# x-release-please-end
