apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base defines dev environment
resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/part-of: __APP_NAME__-dev
  - includeSelectors: true
    pairs:
      environment: dev

replicas:
  - name: __APP_NAME__
    count: 2
